name: Day_One_Recap
run-name: ${{ github.actor }} is recaping day 1

on: 
  push: 
    branches:
    - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  recapping_day_1:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        names: [ john, doe, persona ]
    steps:
    - name: Running a script
      run: echo "Ran a script in ${{github.ref}} for persona ${{matrix.names}}"
    - name: Access repository (using actions)
      uses: actions/checkout@v4
    - name: Run Local Action
      uses: https://github.com/Parul-mahajan/Local-action/blob/main/action.yml
    
    
      
    
    



