name: Day_One_Recap
run-name: ${{ github.actor }} is recaping day 1

on: 
  push: 
    branches:
    - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  recapping_day_1:
    runs-on: ubuntu-latest
    environment: Dev
    strategy:
      matrix: 
        names: [ john, doe, persona ]
    steps:
    - name: Running a script
      run: |
        echo "Ran a script in ${{github.ref}} for persona ${{matrix.names}}"
    - name: Access repository (using actions)
      uses: actions/checkout@v4
    - name: Checkout local action repository
      uses: actions/checkout@v4
      with:
        repository: Parul-mahajan/Local-action
        path: local-action-repo
    - name: Run Local Action
      uses: ./local-action-repo
    - name: Using reusable template
      uses: https://github.com/Parul-mahajan/Local-action/blob/main/.github/workflows/reusable_workflow.yaml
      with:
        param1: 'Hello, world!'


        
  
      
    
    



